name: tests
on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag nepolin/football_tools .
    - name: Verifica el formato
      run: docker run nepolin/football_tools make check
    - name: Corre pruebas y evalua cobertura
      run: docker run nepolin/football_tools make tests
